import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReduxProvider from "@/components/ReduxProvider";
import Providers from "@/components/Providers"; // hydration-safe wrapper
import { NavLayout } from "@/components/NavLayout";
import { AuthGuard } from "@/components/AuthGuard";
import { ErrorBoundary } from "@/components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-gray-900 dark:text-white`}
      >
        <Providers>
          <ReduxProvider>
            <ErrorBoundary>
              <AuthGuard>
                <NavLayout>{children}</NavLayout>
              </AuthGuard>
            </ErrorBoundary>
            <Toaster />
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
